version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - BTCwebhook_static_volume:/BTCwebhook/static
      - BTCwebhook_files_volume:/BTCwebhook/files
    networks:
      - nginx_network

volumes:
  blogpy_static_volume:
    external: true
  blogpy_files_volume:
    external: true
networks:
  nginx_network:
    external: true