# Generated by Django 3.0.7 on 2020-06-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooktest', '0003_auto_20200619_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='addrress',
            new_name='address',
        ),
    ]
